### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by toddmichael** [hashicorp/vault-load-testing#1]
Hello, appreciate this project.  Unfortunately, I'm struggling to get it to work.

## Environment
* Mac
* Python 3.6.6
* Locust 0.8.1
* Vault 0.10.4

## Prepare
Prepare works as expected
```
$ TOKEN=$(cat ~/.vault-token) ./prepare.py --secrets=10
Creating test keys in Vault  [####################################]  100%
```

and `testdata.json` looks right:
```
$ cat testdata.json | jq .
{
  "token": "52480efd-bb44-cf48-d15f-acc20ad91239",
  "num_secrets": 10,
  "secret_size": 1024,
  "transit_size": 1048576,
  "keys": [
    "ab/ab7a03b44ec5d6cac11bcf9feb8ae5b7",
    "2a/2cc2512ad0a8eb05bcdbaaae1ba0f9cc",
    "5d/cbb7336f9a428ab7fdf5dfe008653622",
    "df/ac09d3d0dd3af20a83be99eaec1b3ec6",
    "a9/08c1ee02db4eeda9d8e9b47aa09112ca",
    "8a/be76eff7bfa3c82c73eee8bcb99f7d44",
    "bb/aac1befa0396c3dabff1b7190513da41",
    "ac/5c84521206bebeb9b7d826edd6baccdf",
    "3b/db34ecefcac9b84c3f0beb04a84a1e0f",
    "0c/215acd6f8f277beaa3620b6a246ced24"
  ]
}
```
## Locust Run

Unfortunately when I run `locust` I get this:
```
$ locust -H http://localhost:8200 -c 1 -r 1 --no-web
[2018-08-21 14:02:26,106] stompy.local/INFO/locust.main: Starting Locust 0.8.1
[2018-08-21 14:02:26,107] stompy.local/INFO/locust.runners: Hatching and swarming 1 clients at the rate 1 clients/s...
 Name                                                          # reqs      # fails     Avg     Min     Max  |  Median   req/s
--------------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------------------
 Total                                                              0     0(0.00%)                                       0.00

[2018-08-21 14:02:26,116] stompy.local/ERROR/stderr: Traceback (most recent call last):
  File "/Users/tmichael/.pyenv/versions/3.6.6/lib/python3.6/site-packages/locust/core.py", line 271, in run
    self.execute_next_task()
  File "/Users/tmichael/.pyenv/versions/3.6.6/lib/python3.6/site-packages/locust/core.py", line 297, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/Users/tmichael/.pyenv/versions/3.6.6/lib/python3.6/site-packages/locust/core.py", line 309, in execute_task
    task(self, *args, **kwargs)
  File "/Users/tmichael/Documents/orgs/strata/vault/vault-load-testing/locusts/transit.py", line 23, in encrypt_block
    data = common.random_data(self.locust.testdata['transit_size'])
TypeError: 'NoneType' object is not subscriptable
...
```

Inspecting `self.locust.testdata` from within the function shows:
```
[2018-08-21 14:15:45,078] stompy.local/INFO/stdout: testdata type is None:
```

What am I missing?  Thanks.

**Comment by joemiller** [comment]
Running into this as well. I have no idea how to Locust though. I was able to get a bit further along by calling the setup method to load the testdata.json. I'm not sure how this is supposed to be properly handled.

```
--- a/locusts/__init__.py      2018-08-22 18:23:25.000000000 -0700
+++ b/locusts/__init__.py        2018-08-22 18:13:02.000000000 -0700
@@ -13,6 +13,7 @@
     def __init__(self):
         super().__init__()
         self.client = VaultSession(base_url=self.host)
+        self.setup()

     def setup(self):
         with open('testdata.json', 'r') as f:
```

**Comment by ankitforcode** [comment]
https://github.com/hashicorp/vault-load-testing/pull/3

**Comment by jeffWelling** [comment]
@ankitforcode 

Thanks for your work on that pull request! I've hit the problem mentioned here so I tried your branch but I'm hitting different errors now, I just wanted to double-check that everything was included in the commit for that PR? I know I can sometimes forget to include a piece of code, not accusing you of anything, just sanity-checking. :smile: 

For reference, this is the error I'm getting when I try your branch:

```
[2018-09-27 18:50:51,298] $HOSTNAME/ERROR/stderr: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/locust/core.py", line 271, in run
    self.execute_next_task()
  File "/usr/lib/python3.6/site-packages/locust/core.py", line 297, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/usr/lib/python3.6/site-packages/locust/core.py", line 309, in execute_task
    task(self, *args, **kwargs)
  File "/root/vault-load-testing/locusts/dyn_mongodb.py", line 60, in generate_creds
    r = self.client.get(f'/v1/database/creds/{self.ROLE_NAME}')
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 525, in get
    return self.request('GET', url, **kwargs)
  File "/root/vault-load-testing/locusts/__init__.py", line 107, in request
    '. '.join(response.json()['errors']))
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 896, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

I plan to dig into the error further next week, I'll let you know if I manage to fix my problem.

**Comment by tradel** [comment]
Thanks for reporting the issue. It looks like support for the `setup` and `teardown` methods didn't make it into Locust until version 0.9.0. I was building Locust from source, that's why it worked for me. 

Upgrade Locust with `pip install --upgrade Locust==0.9.0` and it should work. I will update the `requirements.txt` too.
