### ISSUE TITLE
locust fais with following errors on ubuntu

### ISSUE THREAD

**Issue by LeenaSinghal0801** [hashicorp/vault-load-testing#2]
ubuntu@instance-20180910-1716:~/vault-load-testing-master$ /home/ubuntu/.local/bin/locust -H http://10.0.0.8:8222 -c 25 -r 5 --no-web
[2018-09-11 00:53:12,924] instance-20180910-1716/ERROR/stderr: Traceback (most recent call last):
[2018-09-11 00:53:12,925] instance-20180910-1716/ERROR/stderr: File "/home/ubuntu/.local/bin/locust", line 11, in <module>
[2018-09-11 00:53:12,925] instance-20180910-1716/ERROR/stderr:
[2018-09-11 00:53:12,925] instance-20180910-1716/ERROR/stderr: sys.exit(main())
[2018-09-11 00:53:12,925] instance-20180910-1716/ERROR/stderr: File "/home/ubuntu/.local/lib/python2.7/site-packages/locust/main.py", line 391, in main
[2018-09-11 00:53:12,925] instance-20180910-1716/ERROR/stderr:
[2018-09-11 00:53:12,925] instance-20180910-1716/ERROR/stderr: docstring, locusts = load_locustfile(locustfile)
[2018-09-11 00:53:12,926] instance-20180910-1716/ERROR/stderr: File "/home/ubuntu/.local/lib/python2.7/site-packages/locust/main.py", line 358, in load_locustfile
[2018-09-11 00:53:12,926] instance-20180910-1716/ERROR/stderr:
[2018-09-11 00:53:12,926] instance-20180910-1716/ERROR/stderr: imported = __import__(os.path.splitext(locustfile)[0])
[2018-09-11 00:53:12,926] instance-20180910-1716/ERROR/stderr: File "/home/ubuntu/.local/lib/python2.7/site-packages/gevent/builtins.py", line 96, in __import__
[2018-09-11 00:53:12,926] instance-20180910-1716/ERROR/stderr:
[2018-09-11 00:53:12,926] instance-20180910-1716/ERROR/stderr: result = _import(*args, **kwargs)
[2018-09-11 00:53:12,926] instance-20180910-1716/ERROR/stderr: File "/home/ubuntu/vault-load-testing-master/locustfile.py", line 1, in <module>
[2018-09-11 00:53:12,926] instance-20180910-1716/ERROR/stderr:
[2018-09-11 00:53:12,927] instance-20180910-1716/ERROR/stderr: from locusts.key_value import KeyValueLocust
[2018-09-11 00:53:12,927] instance-20180910-1716/ERROR/stderr: File "/home/ubuntu/.local/lib/python2.7/site-packages/gevent/builtins.py", line 96, in __import__
[2018-09-11 00:53:12,927] instance-20180910-1716/ERROR/stderr:
[2018-09-11 00:53:12,927] instance-20180910-1716/ERROR/stderr: result = _import(*args, **kwargs)
[2018-09-11 00:53:12,927] instance-20180910-1716/ERROR/stderr: File "
[2018-09-11 00:53:12,927] instance-20180910-1716/ERROR/stderr: /home/ubuntu/vault-load-testing-master/locusts/__init__.py
[2018-09-11 00:53:12,927] instance-20180910-1716/ERROR/stderr: ", line
[2018-09-11 00:53:12,928] instance-20180910-1716/ERROR/stderr: 34
[2018-09-11 00:53:12,928] instance-20180910-1716/ERROR/stderr:
[2018-09-11 00:53:12,928] instance-20180910-1716/ERROR/stderr:
[2018-09-11 00:53:12,928] instance-20180910-1716/ERROR/stderr: def mount(self, name: str, mount_point: str=None):
[2018-09-11 00:53:12,928] instance-20180910-1716/ERROR/stderr:
[2018-09-11 00:53:12,928] instance-20180910-1716/ERROR/stderr:
[2018-09-11 00:53:12,928] instance-20180910-1716/ERROR/stderr:
[2018-09-11 00:53:12,928] instance-20180910-1716/ERROR/stderr:
[2018-09-11 00:53:12,928] instance-20180910-1716/ERROR/stderr:
[2018-09-11 00:53:12,929] instance-20180910-1716/ERROR/stderr:
[2018-09-11 00:53:12,929] instance-20180910-1716/ERROR/stderr:
[2018-09-11 00:53:12,929] instance-20180910-1716/ERROR/stderr:
[2018-09-11 00:53:12,929] instance-20180910-1716/ERROR/stderr:
[2018-09-11 00:53:12,929] instance-20180910-1716/ERROR/stderr:
[2018-09-11 00:53:12,929] instance-20180910-1716/ERROR/stderr:
[2018-09-11 00:53:12,929] instance-20180910-1716/ERROR/stderr:
[2018-09-11 00:53:12,929] instance-20180910-1716/ERROR/stderr:
[2018-09-11 00:53:12,930] instance-20180910-1716/ERROR/stderr:
[2018-09-11 00:53:12,930] instance-20180910-1716/ERROR/stderr:
[2018-09-11 00:53:12,930] instance-20180910-1716/ERROR/stderr:
[2018-09-11 00:53:12,930] instance-20180910-1716/ERROR/stderr:
[2018-09-11 00:53:12,930] instance-20180910-1716/ERROR/stderr:
[2018-09-11 00:53:12,930] instance-20180910-1716/ERROR/stderr:
[2018-09-11 00:53:12,930] instance-20180910-1716/ERROR/stderr:
[2018-09-11 00:53:12,930] instance-20180910-1716/ERROR/stderr:
[2018-09-11 00:53:12,930] instance-20180910-1716/ERROR/stderr: ^
[2018-09-11 00:53:12,931] instance-20180910-1716/ERROR/stderr: SyntaxError
[2018-09-11 00:53:12,931] instance-20180910-1716/ERROR/stderr: :
[2018-09-11 00:53:12,931] instance-20180910-1716/ERROR/stderr: invalid syntax
[2018-09-11 00:53:12,931] instance-20180910-1716/ERROR/stderr:

**Comment by LeenaSinghal0801** [comment]
Looks like this works for KV version 1 only
